FROM python:3.9-slim

# Install necessary packages
RUN apt-get update && apt-get install -y \
    postgresql-client \
    libpq-dev \
    gcc \
    git && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/dbt

# Copy DBT project and requirements
COPY ./dbt /usr/app/dbt
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Set DBT profiles directory
ENV DBT_PROFILES_DIR=/usr/app/dbt
