default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: staging_layer_db  # this should match your DB service name in docker-compose
      user: ${POSTGRES_STAGING_USER}  # ensure this matches the env variable
      password: ${POSTGRES_STAGING_PASSWORD}  # ensure this matches the env variable
      dbname: ${POSTGRES_STAGING_DB}  # ensure this matches the env variable
      schema: public
      port: 5432
